---
- name: Checkout kernel-ci-frontend code
  git:  repo=https://github.com/kernelci/kernelci-frontend.git
        dest={{ install_base }}/{{ hostname }}
        version={{ git_head }}
        update=yes
  notify:
    - restart-uwsgi
  tags:
    - install
    - app

- name: Fix cloned repo permissions
  file: path={{ install_base }}/{{ hostname }}
        state=directory
        recurse=yes
        owner={{ app_user }}
        group={{ app_user }}
  tags:
    - install
    - app

- name: Install pip requirements
  pip:  requirements={{ install_base }}/{{ hostname }}/requirements.txt
        virtualenv={{ install_base }}/.venv/{{ hostname }}
        extra_args="--upgrade"
  notify:
    - reload-uwsgi
  tags:
    - install
    - app

- name: Fix virtualenv permissions
  file: path={{ install_base }}/.venv/{{ hostname }}
        state=directory
        recurse=yes
        owner={{ app_user }}
        group={{ app_user }}
  tags:
    - install
    - app

- name: Copy app settings file
  template: src=flask_settings
            dest=/etc/linaro/kernelci-frontend.cfg
            owner=root
            group=root
            mode=0644
  notify:
    - restart-uwsgi
  tags:
    - install
    - app
    - secrets

- name: Create empty flask_settings
  file: path=/etc/flask_settings
        owner=root
        group=root
        mode=0644
        state=touch
  tags:
    - install
    - app
